name: Generate scores
on:
  push:
    branches:
      - master

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: master
          path: ./_repo

      - name: Build stats file
        run: |
          cd _repo/_tools/ && yarn install && node compute-stats.js

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: Update scores
          repository: ./_repo
          file_pattern: ./**
          commit_author: The Grasshoppbot <actions@github.com>
