name: Generate scores
on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: master
          path: ./_repo

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: ./_site

      - name: Build site
        run: |
          cd _repo/ && yarn install && gatsby build && cp ./public/* ../_site/

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: Update website
          repository: ./_site
          file_pattern: ./**
          commit_author: The Grasshoppbot <actions@github.com>
